AWSTemplateFormatVersion: '2010-09-09'

Description: Demo Stack

Parameters:  
  BucketName:
    Type: string
    Default: myexperimentbucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    BucketName: !Ref BucketName
